#  KNN

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier
from sklearn.linear_model import LassoCV, Lasso, RidgeCV, Ridge, ElasticNetCV,ElasticNet
from sklearn.metrics import auc, accuracy_score, roc_auc_score, confusion_matrix, r2_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
import sklearn
%matplotlib inline

In [2]:
df=pd.read_csv("winequality-red.csv")

In [3]:
df.head(5)

fixed acidity  volatile acidity  citric acid  residual sugar  chloride  \
0            7.4              0.70         0.00             1.9     0.076   
1            7.8              0.88         0.00             2.6     0.098   
2            7.8              0.76         0.04             2.3     0.092   
3           11.2              0.28         0.56             1.9     0.075   
4            7.4              0.70         0.00             1.9     0.076   

   free sulphur dioxide  total sulphur dioxide  density    PH  sulphate  \
0                  11.0                   34.0   0.9978  3.51      0.56   
1                  25.0                   67.0   0.9968  3.20      0.68   
2                  15.0                   54.0   0.9970  3.26      0.65   
3                  17.0                   60.0   0.9980  3.16      0.58   
4                  11.0                   34.0   0.9978  3.51      0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [4]:
x=df.drop(columns=['quality'])
y=df.quality

In [5]:
x_train, x_test, y_train, y_test= train_test_split(x,y, random_state=20)

In [6]:
knn=KNeighborsClassifier()

In [7]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [8]:
knn.score(x_test, y_test)

0.5175

In [9]:
np.arange(2,30,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [10]:
pram={
    "n_neighbors":np.arange(2,30,2),
    "weights":['uniform','distance'],
    "algorithm":['auto', 'ball_tree', 'kd_tree', 'brute'],
    "leaf_size": np.arange(2,50,2),
    "p": [1,2,3]
    
    
}

In [11]:
grid_knn=GridSearchCV(knn,param_grid=pram,n_jobs=-1,verbose=1, cv=10)

In [12]:
grid_knn.fit(x_train,y_train)

Fitting 10 folds for each of 8064 candidates, totalling 80640 fits


C:\Users\arvin\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 8 members, which is less than n_splits=10.
  warnings.warn(
C:\Users\arvin\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [0.49621849 0.58212885 0.4987535  ...        nan        nan        nan]
  warnings.warn(


GridSearchCV(cv=10, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48]),
                         'n_neighbors': array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]),
                         'p': [1, 2, 3], 'weights': ['uniform', 'distance']},
             verbose=1)

In [ ]:
grid_knn.score(x_test,y_test)

In [ ]:
grid_knn.best_params_

In [ ]:
grid_knn_best=KNeighborsClassifier(n_neighbors=28,algorithm='ball_tree',leaf_size=2,p=1,weights='distance')

In [ ]:
grid_knn_best.fit(x_train,y_train)

In [ ]:
grid_knn_best.score(x_test,y_test)

In [ ]:
grid_knn_best.predict(x_test)


In [26]:
a=[x_test.iloc[0]]

In [27]:
import pickle
pickle.dump(grid_knn_best, open("knn.pkl" , "wb"))

In [28]:
grid_knn_best.predict([x_test.iloc[0]])

C:\Users\arvin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([6], dtype=int64)

In [1]:
from sklearn.svm import SVC
svc=SVC()

In [30]:
svc.fit(x_train,y_train)

SVC()

In [31]:
svc.score(x_test,y_test)

0.5

In [32]:
param ={"kernel":['linear', 'poly', 'rbf', 'sigmoid' ]
       }

svm_grid = GridSearchCV(svc , param_grid=param)
svm_grid.fit(x_train,y_train)

GridSearchCV(estimator=SVC(),
             param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [33]:
svm_grid.score(x_test,y_test)

0.5925

In [35]:
svm_grid.best_params_

{'kernel': 'linear'}

In [37]:
svc1=SVC(kernel='linear')
svc1.fit(x_train,y_train)

SVC(kernel='linear')

In [39]:
svc1.score(x_test,y_test)

0.5925

!pip install cuml

In [29]:
param ={"kernel":['linear', 'poly', 'rbf', 'sigmoid' ],
        'C':[.1,.4 , .6 , 1,2],
        'gamma':[.001,.004,.003]
    } 


In [ ]:
svm_grid_new = GridSearchCV(svc , param_grid=param , verbose=1, n_jobs=-1 )
svm_grid_new.fit(x_train,y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits


# SVR

In [52]:
df1= pd.read_csv("Admission_Prediction.csv")

In [53]:
df1['GRE Score']=df1['GRE Score'].fillna(df1['GRE Score'].mean())

In [54]:
df1['TOEFL Score']=df1['TOEFL Score'].fillna(df1['TOEFL Score'].mean())

In [55]:
df1['University Rating']=df1['University Rating'].fillna(df1['University Rating'].mean())

In [57]:
df1.isna().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [58]:
x=df1.drop(columns=['Chance of Admit', 'Serial No.'])

In [59]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [60]:
y=df1['Chance of Admit']

In [61]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [65]:
x_train, x_test, y_train, y_test= train_test_split(x,y, random_state=20)

In [62]:
from sklearn.svm import SVR

In [63]:
svr= SVR()

In [66]:
svr.fit(x_train, y_train)

SVR()

 #  if we have to check the accuracy of regression model, we are suppose to use R^2
 
 # MSE is mean squsred error that will help to tune a parameter or change the value of the hyper plane

In [68]:
from sklearn.metrics import r2_score

In [69]:
r2_score(y_test, svr.predict(x_test))

0.6460366607697001

In [70]:
svr.predict(x_test)

array([0.8429916 , 0.68933973, 0.88821324, 0.81235388, 0.53542431,
       0.66256689, 0.57760181, 0.82364574, 0.62728543, 0.80711929,
       0.55148183, 0.79357958, 0.58183078, 0.6803638 , 0.66002833,
       0.75157372, 0.70922788, 0.8076968 , 0.68030669, 0.7201224 ,
       0.75518109, 0.51265596, 0.72189765, 0.76099943, 0.81885679,
       0.66136253, 0.55999366, 0.6534701 , 0.87577322, 0.69999593,
       0.68720376, 0.61807948, 0.79901945, 0.5925469 , 0.80513275,
       0.63759733, 0.77442435, 0.58846818, 0.69570226, 0.64684662,
       0.88305102, 0.74965273, 0.71546995, 0.80045255, 0.69201641,
       0.71305465, 0.7168561 , 0.89222725, 0.85012659, 0.53744788,
       0.6695295 , 0.62848758, 0.75689089, 0.69975408, 0.60043674,
       0.73128207, 0.80466681, 0.74546532, 0.78311247, 0.78605358,
       0.75212702, 0.79295728, 0.90400343, 0.86636584, 0.6517938 ,
       0.68063325, 0.78517348, 0.6606029 , 0.65316303, 0.72618474,
       0.80183332, 0.81200814, 0.58352703, 0.62581115, 0.72947

In [72]:
svr.predict([x.iloc[0]])

C:\Users\arvin\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([0.88745066])

In [73]:
y.iloc[0]

0.92

In [74]:
svr.score(x_test,y_test)

0.6460366607697001

# Ensemble techniques in machine learning are a type of machine learning algorithm that combines the predictions of multiple individual models to produce a more accurate prediction. Ensemble techniques can be used for both classification and regression tasks

# bagging and boosting and stacking

#  stacking

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import StackingClassifier, BaggingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV


In [2]:
df2=pd.read_csv('winequality-red.csv')

In [3]:
x=df2.drop(columns=['quality'])
y=df2.quality

In [4]:
train, val_train, test, val_test= train_test_split(x,y, test_size=0.5, random_state=30)

In [5]:
x_train, x_test, y_train, y_test= train_test_split(train,test,random_state=30, test_size=0.10)

In [6]:
knn=KNeighborsClassifier()
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [7]:
knn.score(x_test,y_test)

0.575

In [8]:
svc=SVC()
svc.fit(x_train, y_train)

SVC()

In [9]:
svc.score(x_test,y_test)

0.5125

In [10]:
knn_predicted= knn.predict(val_train)

In [11]:
svc_predicted= svc.predict(val_train)

In [12]:
input3=np.column_stack((knn_predicted,svc_predicted))

In [13]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  6  5
798  6  6
799  5  5

[800 rows x 2 columns]

In [14]:
rf=RandomForestClassifier()

In [15]:
rf.fit(input3,val_test)

RandomForestClassifier()

In [16]:
rf.predict(x_test)

C:\Users\arvin\anaconda3\Lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


ValueError: X has 11 features, but RandomForestClassifier is expecting 2 features as input.

In [110]:
svc_pred=svc.predict(x_test)
knn_pred=knn.predict(x_test)

inp=np.column_stack((knn_pred,svc_pred))

In [111]:
rf.predict(inp)

array([5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 7,
       5, 5, 5, 5, 7, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5,
       6, 7, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 7, 6, 6, 5, 5, 6, 5, 7, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 5, 6, 6, 6, 5, 5, 5], dtype=int64)

In [112]:
rf.score(inp,y_test)

0.5625